# Generated by Django 3.0.6 on 2020-07-05 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('ID_Cargo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('Estado', models.CharField(max_length=1)),
                ('Valor_cargo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoVinculacion',
            fields=[
                ('ID_TipoVinculacion', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=40)),
                ('Estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('ID_Empleado', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=40)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.IntegerField()),
                ('Tipo_Documento', models.CharField(max_length=40)),
                ('ID_Cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Empleado.Cargo')),
                ('ID_TipoVinculacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Empleado.TipoVinculacion')),
            ],
        ),
    ]
