# Generated by Django 3.0.6 on 2020-07-05 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_Empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('ID_Periodo', models.AutoField(primary_key=True, serialize=False)),
                ('Anual', models.CharField(max_length=40)),
                ('Mes', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('ID_Nomina', models.AutoField(primary_key=True, serialize=False)),
                ('Valor_Pagar', models.FloatField()),
                ('Subtotal', models.FloatField()),
                ('Total', models.FloatField()),
                ('Estado', models.CharField(max_length=1)),
                ('ID_Empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Empleado.Empleado')),
                ('ID_Periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Nomina.Periodo')),
            ],
        ),
    ]
