# Generated by Django 3.0.6 on 2020-07-05 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_Empleado', '0001_initial'),
        ('Gestion_Nomina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasAdicionales',
            fields=[
                ('ID_HorasAdicionales', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('Valor', models.FloatField()),
                ('Estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteHoras',
            fields=[
                ('ID_ReporteHoras', models.AutoField(primary_key=True, serialize=False)),
                ('Numero_Horas', models.IntegerField()),
                ('ID_Empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Empleado.Empleado')),
                ('ID_Periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Nomina.Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Parafiscales',
            fields=[
                ('ID_PArafiscales', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('Valor', models.FloatField()),
                ('Estado', models.CharField(max_length=1)),
                ('Id_TipoVinculacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Empleado.TipoVinculacion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleParafiscales',
            fields=[
                ('ID_DetalleParafiscal', models.AutoField(primary_key=True, serialize=False)),
                ('Total_Parafiscales', models.FloatField()),
                ('ID_Nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Nomina.Nomina')),
                ('ID_Parafiscales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Tiempo.Parafiscales')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleHoras',
            fields=[
                ('ID_DetalleHoras', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.FloatField()),
                ('Cantidad', models.IntegerField()),
                ('ID_HorasAdicionales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Tiempo.HorasAdicionales')),
                ('ID_Nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Nomina.Nomina')),
            ],
        ),
    ]
